import type { Department, DepartmentCategory, DepartmentRelation, ScrapeJob } from "@/lib/types";

export const categories: DepartmentCategory[] = [
  { id: "admissions", name: "入試", slug: "admissions", description: "受験と出願に関する窓口", sortOrder: 1 },
  { id: "tuition", name: "学費", slug: "tuition", description: "納付や証明に関する窓口", sortOrder: 2 },
  { id: "scholarship", name: "奨学金", slug: "scholarship", description: "奨学金と減免の窓口", sortOrder: 3 },
  { id: "student-life", name: "学生生活", slug: "student-life", description: "学生生活全般を支える窓口", sortOrder: 4 },
  { id: "career", name: "就職", slug: "career", description: "進路とキャリア支援の窓口", sortOrder: 5 },
  { id: "it", name: "情報システム", slug: "it", description: "情報環境とアカウント支援の窓口", sortOrder: 6 },
  { id: "global", name: "留学", slug: "global", description: "海外派遣と国際交流の窓口", sortOrder: 7 },
  { id: "support", name: "相談窓口", slug: "support", description: "相談と支援の窓口", sortOrder: 8 },
  { id: "correspondence", name: "通信教育部", slug: "correspondence", description: "通信教育部向けの窓口", sortOrder: 9 },
];

export const departments: Department[] = [
  {
    id: "dept-01",
    slug: "admissions-center",
    name: "入学センター",
    officialName: "法政大学 入学センター",
    shortDescription: "出願方法、入試制度、オープンキャンパスに関する一次窓口。",
    longDescription:
      "法政大学への受験を検討している人向けに、学部ごとの入試制度、出願スケジュール、説明会情報を案内する窓口です。受験前の基礎的な相談を受け止め、必要に応じて学部や他部署へつなぎます。",
    categoryId: "admissions",
    audienceTypes: ["受験検討者", "保護者"],
    campusTypes: ["共通"],
    courseTypes: ["通学課程"],
    phone: "03-3264-9300",
    email: "nyushi@hosei.ac.jp",
    inquiryUrl: "https://www.hosei.ac.jp/admission/",
    officeHours: "平日 9:00-17:00",
    tags: ["入試", "出願", "オープンキャンパス"],
    inquiryExamples: ["総合型選抜の出願条件を知りたい", "学部別の入試日程を確認したい", "説明会や個別相談会の参加方法を知りたい"],
    cautionNotes: ["在学生向けの履修相談や学費相談は別窓口です。", "学部固有の提出書類は学部案内と併読してください。"],
    sourceUrls: ["https://www.hosei.ac.jp/admission/"],
    sourceHash: "src-admissions-20260410",
    status: "active",
    lastScrapedAt: "2026-04-09T09:10:00+09:00",
    updatedAt: "2026-04-09T14:00:00+09:00",
    relatedSlugs: ["finance-division", "correspondence-education-office"],
  },
  {
    id: "dept-02",
    slug: "finance-division",
    name: "経理課",
    officialName: "法政大学 財務部 経理課",
    shortDescription: "学費納入、納付証明、返金や延納相談の起点となる窓口。",
    longDescription:
      "学費の納付方法、納入期限、延納手続き、証明書発行など、お金に関わる問い合わせを扱います。奨学金関連の相談と並走する場面が多いため、制度確認後に奨学金窓口へ回す導線を持っています。",
    categoryId: "tuition",
    audienceTypes: ["学生", "保護者"],
    campusTypes: ["共通"],
    courseTypes: ["通学課程", "通信教育部"],
    phone: "03-3264-9590",
    email: "keiri@hosei.ac.jp",
    inquiryUrl: "https://www.hosei.ac.jp/campuslife/fees/",
    officeHours: "平日 9:00-17:00",
    tags: ["学費", "納入", "延納", "証明書"],
    inquiryExamples: ["学費の振込期限を確認したい", "納付証明書の発行方法を知りたい", "延納の対象条件を相談したい"],
    cautionNotes: ["奨学金の審査状況そのものは奨学金担当へ確認が必要です。", "通信教育部の学費は制度が異なるため案内先が変わることがあります。"],
    sourceUrls: ["https://www.hosei.ac.jp/campuslife/fees/"],
    sourceHash: "src-finance-20260410",
    status: "active",
    lastScrapedAt: "2026-04-09T09:14:00+09:00",
    updatedAt: "2026-04-08T18:30:00+09:00",
    relatedSlugs: ["scholarship-support-desk", "correspondence-education-office", "admissions-center"],
  },
  {
    id: "dept-03",
    slug: "scholarship-support-desk",
    name: "奨学金窓口",
    officialName: "法政大学 学生センター 奨学金担当",
    shortDescription: "奨学金申請、家計急変、減免制度の相談窓口。",
    longDescription:
      "日本学生支援機構や大学独自奨学金、家計急変時の支援制度などを案内する窓口です。申請締切や必要書類の確認を通じて、学生が制度を取りこぼさないようにサポートします。",
    categoryId: "scholarship",
    audienceTypes: ["学生", "保護者"],
    campusTypes: ["市ケ谷", "多摩", "小金井"],
    courseTypes: ["通学課程"],
    phone: "03-3264-9486",
    email: "scholarship@hosei.ac.jp",
    inquiryUrl: "https://www.hosei.ac.jp/campuslife/scholarship/",
    officeHours: "平日 9:00-17:00",
    tags: ["奨学金", "減免", "家計急変"],
    inquiryExamples: ["給付型奨学金の応募条件を知りたい", "家計急変時の緊急支援を相談したい", "提出書類の不備を確認したい"],
    cautionNotes: ["学費の振込スケジュール確認は経理課との併用が必要です。", "通信教育部向け制度は別ページでの案内が中心です。"],
    sourceUrls: ["https://www.hosei.ac.jp/campuslife/scholarship/"],
    sourceHash: "src-scholarship-20260410",
    status: "active",
    lastScrapedAt: "2026-04-09T09:18:00+09:00",
    updatedAt: "2026-04-07T12:00:00+09:00",
    relatedSlugs: ["finance-division", "student-center-ichigaya", "student-counseling-room"],
  },
  {
    id: "dept-04",
    slug: "student-center-ichigaya",
    name: "学生センター（市ケ谷）",
    officialName: "法政大学 学生センター 市ケ谷学生生活課",
    shortDescription: "学生生活、課外活動、学生証、各種届出を扱う市ケ谷の総合窓口。",
    longDescription:
      "学生生活上の手続きや課外活動支援、学生証関連、休学や住所変更など、幅広い相談を受ける総合窓口です。困りごとの一次受けとして他部署とのハブにもなります。",
    categoryId: "student-life",
    audienceTypes: ["学生"],
    campusTypes: ["市ケ谷"],
    courseTypes: ["通学課程"],
    phone: "03-3264-9475",
    email: "gakusei-i@hosei.ac.jp",
    inquiryUrl: "https://www.hosei.ac.jp/campuslife/support/",
    officeHours: "平日 9:00-17:00",
    tags: ["学生生活", "学生証", "課外活動", "届出"],
    inquiryExamples: ["学生証の再発行を相談したい", "休学や復学の手順を知りたい", "課外活動の手続き窓口を知りたい"],
    cautionNotes: ["履修制度や成績の詳細は学部事務が担当する場合があります。", "心身の不調に関する相談は学生相談室への案内が優先されます。"],
    sourceUrls: ["https://www.hosei.ac.jp/campuslife/support/"],
    sourceHash: "src-student-life-ichigaya-20260410",
    status: "active",
    lastScrapedAt: "2026-04-09T09:22:00+09:00",
    updatedAt: "2026-04-06T10:20:00+09:00",
    relatedSlugs: ["student-counseling-room", "scholarship-support-desk", "it-support-desk"],
  },
  {
    id: "dept-05",
    slug: "student-center-tama",
    name: "学生センター（多摩）",
    officialName: "法政大学 学生センター 多摩学生生活課",
    shortDescription: "多摩キャンパス向けの学生生活支援と手続き窓口。",
    longDescription:
      "多摩キャンパスの学生生活を支える窓口で、通学上の相談、学生証、課外活動や生活面の手続きなどを案内します。キャンパス固有の事情があるため、市ケ谷とは別導線で案内します。",
    categoryId: "student-life",
    audienceTypes: ["学生"],
    campusTypes: ["多摩"],
    courseTypes: ["通学課程"],
    phone: "042-783-2151",
    email: "gakusei-t@hosei.ac.jp",
    inquiryUrl: "https://www.hosei.ac.jp/campuslife/support/tama/",
    officeHours: "平日 9:00-17:00",
    tags: ["多摩", "学生生活", "届出"],
    inquiryExamples: ["多摩キャンパスの学生証再発行をしたい", "落とし物や施設利用の窓口を知りたい", "課外活動の手続きを確認したい"],
    cautionNotes: ["就職支援はキャリアセンターへの接続が優先です。", "相談内容によっては学生相談室や奨学金担当へ引き継ぎます。"],
    sourceUrls: ["https://www.hosei.ac.jp/campuslife/support/tama/"],
    sourceHash: "src-student-life-tama-20260410",
    status: "active",
    lastScrapedAt: "2026-04-09T09:25:00+09:00",
    updatedAt: "2026-03-28T16:00:00+09:00",
    relatedSlugs: ["career-center", "student-counseling-room"],
  },
  {
    id: "dept-06",
    slug: "career-center",
    name: "キャリアセンター",
    officialName: "法政大学 キャリアセンター",
    shortDescription: "就職活動、インターン、進路相談の総合窓口。",
    longDescription:
      "就職活動の相談、ガイダンス、インターンシップ、履歴書添削など、進路形成を幅広く支援する窓口です。学生生活上の悩みと接続することも多く、学生センターや相談室との連携が重要です。",
    categoryId: "career",
    audienceTypes: ["学生"],
    campusTypes: ["市ケ谷", "多摩", "小金井"],
    courseTypes: ["通学課程"],
    phone: "03-3264-9604",
    email: "career@hosei.ac.jp",
    inquiryUrl: "https://www.hosei.ac.jp/careercenter/",
    officeHours: "平日 9:00-17:00",
    tags: ["就職", "インターン", "キャリア"],
    inquiryExamples: ["面接練習を申し込みたい", "学内企業説明会の情報を知りたい", "就職活動の不安を相談したい"],
    cautionNotes: ["学部必修のキャリア科目は学部事務の案内が必要なことがあります。", "メンタル面の支援が主目的なら学生相談室を優先してください。"],
    sourceUrls: ["https://www.hosei.ac.jp/careercenter/"],
    sourceHash: "src-career-20260410",
    status: "active",
    lastScrapedAt: "2026-04-09T09:28:00+09:00",
    updatedAt: "2026-04-01T11:30:00+09:00",
    relatedSlugs: ["student-center-tama", "student-counseling-room", "global-education-center"],
  },
  {
    id: "dept-07",
    slug: "it-support-desk",
    name: "情報システム部",
    officialName: "法政大学 情報システム部 サポート窓口",
    shortDescription: "ネットワーク、アカウント、システム利用に関する窓口。",
    longDescription:
      "学内ネットワーク、Microsoft 365、学習支援システム、アカウント障害など、デジタル環境の利用に関する問い合わせを受ける窓口です。学生センターや通信教育部から案内されることが多い部署です。",
    categoryId: "it",
    audienceTypes: ["学生", "教職員"],
    campusTypes: ["共通"],
    courseTypes: ["通学課程", "通信教育部"],
    phone: "03-3264-9388",
    email: "itsupport@hosei.ac.jp",
    inquiryUrl: "https://www.hosei.ac.jp/icts/",
    officeHours: "平日 9:00-17:00",
    tags: ["システム", "アカウント", "Wi-Fi"],
    inquiryExamples: ["学習支援システムにログインできない", "学内Wi-Fiの設定方法を知りたい", "メールアカウントの初期化を依頼したい"],
    cautionNotes: ["履修登録そのもののルール説明は学部事務や学生センターに確認してください。", "パスワード障害は本人確認が必要なため即時解決できない場合があります。"],
    sourceUrls: ["https://www.hosei.ac.jp/icts/"],
    sourceHash: "src-it-20260410",
    status: "active",
    lastScrapedAt: "2026-04-09T09:31:00+09:00",
    updatedAt: "2026-04-02T08:15:00+09:00",
    relatedSlugs: ["student-center-ichigaya", "correspondence-education-office"],
  },
  {
    id: "dept-08",
    slug: "global-education-center",
    name: "グローバル教育センター",
    officialName: "法政大学 グローバル教育センター",
    shortDescription: "留学、海外研修、国際交流プログラムの窓口。",
    longDescription:
      "交換留学や短期研修、語学プログラムなど、海外経験を支える制度を案内する窓口です。応募時期や条件の確認から、渡航前準備まで複数段階で学生を支援します。",
    categoryId: "global",
    audienceTypes: ["学生", "受験検討者"],
    campusTypes: ["市ケ谷"],
    courseTypes: ["通学課程"],
    phone: "03-3264-9338",
    email: "global@hosei.ac.jp",
    inquiryUrl: "https://www.hosei.ac.jp/geo/",
    officeHours: "平日 9:00-17:00",
    tags: ["留学", "国際交流", "海外研修"],
    inquiryExamples: ["交換留学の応募条件を知りたい", "短期語学研修の費用感を確認したい", "渡航前の手続き相談をしたい"],
    cautionNotes: ["奨学金支援と併せて確認する場合は奨学金窓口も参照してください。", "就職活動との両立相談はキャリアセンターと併用すると整理しやすいです。"],
    sourceUrls: ["https://www.hosei.ac.jp/geo/"],
    sourceHash: "src-global-20260410",
    status: "active",
    lastScrapedAt: "2026-04-09T09:34:00+09:00",
    updatedAt: "2026-04-03T12:00:00+09:00",
    relatedSlugs: ["career-center", "scholarship-support-desk"],
  },
  {
    id: "dept-09",
    slug: "student-counseling-room",
    name: "学生相談室",
    officialName: "法政大学 学生相談室",
    shortDescription: "心身の悩み、学業継続の不安、対人関係などの相談窓口。",
    longDescription:
      "学業、生活、対人関係、心身の不調など、学生が抱えるさまざまな悩みを安心して相談できる窓口です。学生センターやキャリアセンターからの案内先として機能し、必要に応じて学内外の支援につなぎます。",
    categoryId: "support",
    audienceTypes: ["学生"],
    campusTypes: ["市ケ谷", "多摩", "小金井"],
    courseTypes: ["通学課程"],
    phone: "03-3264-9479",
    email: "soudan@hosei.ac.jp",
    inquiryUrl: "https://www.hosei.ac.jp/campuslife/counseling/",
    officeHours: "平日 10:00-17:00",
    tags: ["相談", "メンタルヘルス", "学生支援"],
    inquiryExamples: ["授業に通うのがつらい状況を相談したい", "対人関係の悩みを話したい", "休学を考える前に相談したい"],
    cautionNotes: ["緊急性が高い場合は学外の緊急支援窓口も併用してください。", "各種制度手続きそのものは担当部署の確認が必要です。"],
    sourceUrls: ["https://www.hosei.ac.jp/campuslife/counseling/"],
    sourceHash: "src-counseling-20260410",
    status: "active",
    lastScrapedAt: "2026-04-09T09:37:00+09:00",
    updatedAt: "2026-02-18T15:00:00+09:00",
    relatedSlugs: ["student-center-ichigaya", "career-center", "scholarship-support-desk"],
  },
  {
    id: "dept-10",
    slug: "correspondence-education-office",
    name: "通信教育事務部",
    officialName: "法政大学 通信教育部 事務部",
    shortDescription: "通信教育部の履修、学費、学習支援を扱う専用窓口。",
    longDescription:
      "通信教育部に所属する学生の学習支援、履修、スクーリング、学費関連などを一括で案内する窓口です。通学課程とは制度が異なるため、誤案内を減らすための専用導線として配置しています。",
    categoryId: "correspondence",
    audienceTypes: ["通信教育部学生", "受験検討者"],
    campusTypes: ["共通"],
    courseTypes: ["通信教育部"],
    phone: "03-3264-6150",
    email: "tsushin@hosei.ac.jp",
    inquiryUrl: "https://www.tsukyo.hosei.ac.jp/",
    officeHours: "平日 9:00-17:00 / 土曜 9:00-12:00",
    tags: ["通信教育部", "スクーリング", "履修", "学費"],
    inquiryExamples: ["通信教育部の出願方法を知りたい", "スクーリング申込の流れを確認したい", "学費や教材に関する質問をしたい"],
    cautionNotes: ["通学課程の学生は原則として別窓口です。", "アカウント障害は情報システム部と連携が必要です。"],
    sourceUrls: ["https://www.tsukyo.hosei.ac.jp/"],
    sourceHash: "src-correspondence-20260410",
    status: "active",
    lastScrapedAt: "2026-04-09T09:40:00+09:00",
    updatedAt: "2026-03-20T09:00:00+09:00",
    relatedSlugs: ["finance-division", "it-support-desk", "admissions-center"],
  },
];

export const relations: DepartmentRelation[] = [
  {
    id: "rel-01",
    fromDepartmentId: "dept-01",
    toDepartmentId: "dept-10",
    relationType: "misroute",
    label: "通学課程と通信教育部で誤問い合わせが起きやすい",
    weight: 3,
    note: "出願相談の入口は似ていても制度が大きく異なるため、早い段階で切り分ける必要があります。",
  },
  {
    id: "rel-02",
    fromDepartmentId: "dept-02",
    toDepartmentId: "dept-03",
    relationType: "journey",
    label: "学費相談から奨学金相談へつながりやすい",
    weight: 3,
    note: "納付難の相談では、延納と奨学金の両方を案内することが多いです。",
  },
  {
    id: "rel-03",
    fromDepartmentId: "dept-03",
    toDepartmentId: "dept-04",
    relationType: "collaboration",
    label: "学生生活上の困りごとと制度支援を連携",
    weight: 2,
    note: "生活面の相談から奨学金制度へ接続するケースがあります。",
  },
  {
    id: "rel-04",
    fromDepartmentId: "dept-04",
    toDepartmentId: "dept-05",
    relationType: "sameCategory",
    label: "同カテゴリのキャンパス別窓口",
    weight: 2,
    note: "学生センターはキャンパスごとに担当が分かれています。",
  },
  {
    id: "rel-05",
    fromDepartmentId: "dept-04",
    toDepartmentId: "dept-09",
    relationType: "journey",
    label: "生活相談から相談室へ",
    weight: 2,
    note: "制度や手続きの相談の途中で、相談室の利用が適切になる場合があります。",
  },
  {
    id: "rel-06",
    fromDepartmentId: "dept-05",
    toDepartmentId: "dept-06",
    relationType: "journey",
    label: "多摩の学生生活相談から進路相談へ",
    weight: 2,
    note: "進路不安が背景にある場合、キャリアセンターへ案内されます。",
  },
  {
    id: "rel-07",
    fromDepartmentId: "dept-06",
    toDepartmentId: "dept-09",
    relationType: "collaboration",
    label: "進路不安と心理的支援の連携",
    weight: 2,
    note: "就職活動の不安が大きい学生を相談室へつなぐケースがあります。",
  },
  {
    id: "rel-08",
    fromDepartmentId: "dept-06",
    toDepartmentId: "dept-08",
    relationType: "collaboration",
    label: "留学と就職準備の連携",
    weight: 1,
    note: "留学のタイミングとキャリア形成を並行して相談するケースを想定しています。",
  },
  {
    id: "rel-09",
    fromDepartmentId: "dept-07",
    toDepartmentId: "dept-10",
    relationType: "collaboration",
    label: "通信教育部のシステム障害対応",
    weight: 2,
    note: "学習システムや認証トラブルでは両部署の連携が必要です。",
  },
  {
    id: "rel-10",
    fromDepartmentId: "dept-07",
    toDepartmentId: "dept-04",
    relationType: "misroute",
    label: "履修制度とシステム障害の切り分け",
    weight: 2,
    note: "履修ルールの質問なのか、ログイン障害なのかを初期で切り分けます。",
  },
  {
    id: "rel-11",
    fromDepartmentId: "dept-08",
    toDepartmentId: "dept-03",
    relationType: "journey",
    label: "留学支援から奨学金確認へ",
    weight: 1,
    note: "留学関連の費用相談では奨学金制度の併用確認が必要です。",
  },
  {
    id: "rel-12",
    fromDepartmentId: "dept-02",
    toDepartmentId: "dept-10",
    relationType: "misroute",
    label: "通学課程と通信教育部の学費相談を切り分け",
    weight: 3,
    note: "経理課が一次受けになっても、最終案内先は通信教育事務部になることがあります。",
  },
  {
    id: "rel-13",
    fromDepartmentId: "dept-03",
    toDepartmentId: "dept-09",
    relationType: "collaboration",
    label: "経済的不安と生活支援の連携",
    weight: 1,
    note: "金銭的な不安が心理的負担につながるケースを想定しています。",
  },
  {
    id: "rel-14",
    fromDepartmentId: "dept-01",
    toDepartmentId: "dept-02",
    relationType: "journey",
    label: "受験前後の学費確認導線",
    weight: 1,
    note: "入学前に費用感を確認したい問い合わせが続くことがあります。",
  },
];

export const scrapeJobs: ScrapeJob[] = [
  {
    id: "job-01",
    targetUrl: "https://www.hosei.ac.jp/admission/",
    status: "success",
    startedAt: "2026-04-09T09:00:00+09:00",
    finishedAt: "2026-04-09T09:06:00+09:00",
    resultSummary: "公式問い合わせページを再取込し、2件の差分を検出しました。",
  },
  {
    id: "job-02",
    targetUrl: "https://www.tsukyo.hosei.ac.jp/",
    status: "running",
    startedAt: "2026-04-10T08:30:00+09:00",
    finishedAt: "2026-04-10T08:34:00+09:00",
    resultSummary: "通信教育部のページを解析中です。",
  },
  {
    id: "job-03",
    targetUrl: "https://www.hosei.ac.jp/campuslife/support/",
    status: "failed",
    startedAt: "2026-04-08T07:00:00+09:00",
    finishedAt: "2026-04-08T07:05:00+09:00",
    resultSummary: "学生生活ページの取得に失敗しました。",
    errorMessage: "スクレイピング先のDOM構造変更を検知しました。CSSセレクタの見直しが必要です。",
  },
];

export function getDepartmentBySlug(slug: string) {
  return departments.find((department) => department.slug === slug);
}

export function getCategoryById(categoryId: string) {
  return categories.find((category) => category.id === categoryId);
}
