import type { Department, DepartmentCategory, DepartmentRelation, ScrapeJob } from "@/lib/types";

const CONTACT_PAGE_URL = "https://www.hosei.ac.jp/toiawase/";
const ADMISSION_URL = "https://www.hosei.ac.jp/admission/";
const CAREER_URL = "https://www.hosei.ac.jp/careercenter/";
const GLOBAL_URL = "https://www.global.hosei.ac.jp/";
const CORRESPONDENCE_URL = "https://www.tsukyo.hosei.ac.jp/";
const STUDENT_GUIDE_URL = "https://www.hosei.ac.jp/campuslife/";

const SCRAPED_AT = "2026-04-10T22:20:00+09:00";
const UPDATED_AT = "2026-04-10T22:40:00+09:00";

type DepartmentSeed = Omit<Department, "id" | "sourceHash" | "lastScrapedAt" | "updatedAt">;

type FacultyConfig = {
  slug: string;
  name: string;
  categoryId: string;
  campus: string;
  phone: string;
  officeHours: string;
};

type GraduateConfig = {
  slug: string;
  name: string;
  categoryId: string;
  campusTypes: string[];
  phone: string;
  officeHours: string;
  officialName: string;
  tags: string[];
  inquiryExamples: string[];
};

function office(seed: DepartmentSeed, index: number): Department {
  return {
    id: `dept-${String(index + 1).padStart(2, "0")}`,
    sourceHash: `src-${seed.slug}-20260410`,
    lastScrapedAt: SCRAPED_AT,
    updatedAt: UPDATED_AT,
    ...seed,
  };
}

function facultyOffice(config: FacultyConfig): DepartmentSeed {
  return {
    slug: config.slug,
    name: `${config.name}事務`,
    officialName: `法政大学 ${config.name} 事務室`,
    shortDescription: `${config.name}の履修、成績、試験、学籍を扱う学部窓口。`,
    longDescription:
      `${config.name}に所属する学生や受験検討者向けに、履修登録、試験、成績、休学・復学、卒業要件などの学部固有の案内を行う窓口です。学部ごとの提出書類や運用ルールを確認したいときの起点として使えます。`,
    categoryId: config.categoryId,
    audienceTypes: ["在学生", "受験検討者", "保証人"],
    campusTypes: [config.campus],
    courseTypes: ["通学課程"],
    phone: config.phone,
    email: "公式ページ参照",
    inquiryUrl: CONTACT_PAGE_URL,
    officeHours: config.officeHours,
    tags: [config.name, "履修", "成績", "学籍"],
    inquiryExamples: [
      `${config.name}の履修登録ルールを確認したい`,
      `${config.name}の試験や成績について相談したい`,
      `${config.name}の休学・復学手続きを知りたい`,
    ],
    cautionNotes: [
      "奨学金や学生生活費の相談は学生センター系の窓口が担当です。",
      "入試制度全般は入学センターの案内と併せて確認すると安全です。",
    ],
    sourceUrls: [CONTACT_PAGE_URL],
    status: "active",
    relatedSlugs: ["admissions-center", "student-center", "career-center"],
  };
}

function graduateOffice(config: GraduateConfig): DepartmentSeed {
  return {
    slug: config.slug,
    name: config.name,
    officialName: config.officialName,
    shortDescription: `${config.name}に含まれる大学院の履修・入試・研究指導を扱う窓口。`,
    longDescription:
      `${config.name}に属する研究科・インスティテュートの入試案内、履修、研究指導、論文提出、学位申請などを受け持つ窓口です。学部窓口とは制度が異なるため、大学院関連の相談はこの窓口から始めると導線が安定します。`,
    categoryId: config.categoryId,
    audienceTypes: ["大学院生", "受験検討者", "研究指導教員"],
    campusTypes: config.campusTypes,
    courseTypes: ["大学院"],
    phone: config.phone,
    email: "公式ページ参照",
    inquiryUrl: CONTACT_PAGE_URL,
    officeHours: config.officeHours,
    tags: config.tags,
    inquiryExamples: config.inquiryExamples,
    cautionNotes: [
      "研究費や外部資金に関する事務は研究開発センターと連携する場合があります。",
      "証明書発行や共通手続は所属制度ごとの差があるため公式案内も確認してください。",
    ],
    sourceUrls: [CONTACT_PAGE_URL],
    status: "active",
    relatedSlugs: ["certificate-guidance", "research-development-center", "admissions-center"],
  };
}

export const categories: DepartmentCategory[] = [
  { id: "admissions-common", name: "入試・共通手続", slug: "admissions-common", description: "入試、出願、証明書などの共通窓口", sortOrder: 1 },
  { id: "finance-student-support", name: "学費・学生支援", slug: "finance-student-support", description: "学費、奨学金、学生生活支援の窓口", sortOrder: 2 },
  { id: "learning-it-consultation", name: "学習・IT・相談", slug: "learning-it-consultation", description: "学習支援、IT、相談系の窓口", sortOrder: 3 },
  { id: "career-global-diversity", name: "キャリア・国際", slug: "career-global-diversity", description: "就職、留学、キャリア形成の窓口", sortOrder: 4 },
  { id: "research-public-alumni", name: "研究・広報・卒業生", slug: "research-public-alumni", description: "研究支援、広報、卒業生連携の窓口", sortOrder: 5 },
  { id: "ichigaya-faculty", name: "市ケ谷学部", slug: "ichigaya-faculty", description: "市ケ谷キャンパスの学部事務", sortOrder: 6 },
  { id: "tama-faculty", name: "多摩学部", slug: "tama-faculty", description: "多摩キャンパスの学部事務", sortOrder: 7 },
  { id: "koganei-faculty", name: "小金井学部", slug: "koganei-faculty", description: "小金井キャンパスの学部事務", sortOrder: 8 },
  { id: "graduate-school", name: "大学院・専門職", slug: "graduate-school", description: "大学院と専門職大学院の窓口", sortOrder: 9 },
  { id: "correspondence-attached", name: "通信教育・付属校", slug: "correspondence-attached", description: "通信教育部と付属校の窓口", sortOrder: 10 },
];

const supportSeeds: DepartmentSeed[] = [
  {
    slug: "admissions-center",
    name: "入学センター",
    officialName: "法政大学 入学センター",
    shortDescription: "出願方法、入試制度、オープンキャンパスに関する一次窓口。",
    longDescription:
      "法政大学への受験を検討している人向けに、学部ごとの入試制度、出願スケジュール、説明会情報を案内する窓口です。受験前の基礎的な相談を受け止め、必要に応じて学部や他部署へつなぎます。",
    categoryId: "admissions-common",
    audienceTypes: ["受験検討者", "保護者"],
    campusTypes: ["共通"],
    courseTypes: ["通学課程", "大学院", "専門職大学院"],
    phone: "03-3264-9300",
    email: "nyushi@hosei.ac.jp",
    inquiryUrl: ADMISSION_URL,
    officeHours: "平日 9:00-17:00",
    tags: ["入試", "出願", "オープンキャンパス"],
    inquiryExamples: ["総合型選抜の出願条件を知りたい", "学部別の入試日程を確認したい", "説明会や個別相談会の参加方法を知りたい"],
    cautionNotes: ["在学生向けの履修相談や学費相談は別窓口です。", "学部固有の提出書類は学部案内と併せて確認してください。"],
    sourceUrls: [ADMISSION_URL],
    status: "active",
    relatedSlugs: ["finance-division", "student-center", "correspondence-education-office"],
  },
  {
    slug: "finance-division",
    name: "財務部財務課",
    officialName: "法政大学 財務部財務課",
    shortDescription: "学費の納入、納付方法、口座振替に関する共通窓口。",
    longDescription:
      "学部・大学院・専門職大学院・通信教育部の学費制度に関する入り口として、納入方法、口座振替、納付期限などを案内する窓口です。制度ごとに最終案内先が変わる場合もあるため、まず共通ルールを確認したいときに向いています。",
    categoryId: "finance-student-support",
    audienceTypes: ["在学生", "保証人", "大学院生"],
    campusTypes: ["共通"],
    courseTypes: ["通学課程", "大学院", "専門職大学院", "通信教育部"],
    phone: "03-3264-9270",
    email: "公式ページ参照",
    inquiryUrl: CONTACT_PAGE_URL,
    officeHours: "平日 9:00-17:00",
    tags: ["学費", "口座振替", "納入"],
    inquiryExamples: ["学費の納入期限を確認したい", "学費の口座振替の手続きを知りたい", "学費制度の区分を確認したい"],
    cautionNotes: ["奨学金の申請状況そのものは学生センター側の確認が必要です。", "学部・大学院・通信教育部で制度が異なるため、最終案内先が分かれることがあります。"],
    sourceUrls: [CONTACT_PAGE_URL],
    status: "active",
    relatedSlugs: ["scholarship-support-desk", "certificate-guidance", "correspondence-education-office"],
  },
  {
    slug: "scholarship-support-desk",
    name: "奨学金窓口",
    officialName: "法政大学 学生センター 奨学金担当",
    shortDescription: "奨学金、住まい、アルバイトなど生活費に近い相談窓口。",
    longDescription:
      "学生センターの中でも奨学金や生活支援に近い相談を受ける窓口です。市ケ谷・多摩・小金井で担当電話が分かれており、奨学金制度、アルバイト紹介、住まい紹介など学生生活費に関わる相談へつながります。",
    categoryId: "finance-student-support",
    audienceTypes: ["在学生", "保証人"],
    campusTypes: ["市ケ谷", "多摩", "小金井"],
    courseTypes: ["通学課程"],
    phone: "市ケ谷 03-3264-9486 / 多摩 042-783-2151・2152 / 小金井 042-387-6011",
    email: "公式ページ参照",
    inquiryUrl: CONTACT_PAGE_URL,
    officeHours: "平日 9:00-17:00 または 10:00-17:00 / 土 一部閉室",
    tags: ["奨学金", "住まい", "アルバイト"],
    inquiryExamples: ["奨学金制度の申請方法を知りたい", "アルバイト紹介や部屋紹介の案内を受けたい", "家計急変時の支援制度を相談したい"],
    cautionNotes: ["学費の納付方法そのものは財務部財務課の案内が起点です。", "通信教育部の支援制度は別制度のため専用窓口確認が必要です。"],
    sourceUrls: [CONTACT_PAGE_URL],
    status: "active",
    relatedSlugs: ["finance-division", "student-center", "student-counseling-room"],
  },
  {
    slug: "student-center",
    name: "学生センター",
    officialName: "法政大学 学生センター",
    shortDescription: "学生生活、課外活動、学生支援制度の総合窓口。",
    longDescription:
      "学生生活全般の総合窓口として、奨学金、課外活動、学生支援制度、生活相談の振り分けを行います。市ケ谷・多摩・小金井で担当課が分かれますが、学生生活関連の相談先に迷ったときの起点として使えます。",
    categoryId: "finance-student-support",
    audienceTypes: ["在学生"],
    campusTypes: ["市ケ谷", "多摩", "小金井"],
    courseTypes: ["通学課程"],
    phone: "市ケ谷 03-3264-9476 / 多摩 042-783-2157 / 小金井 042-387-6042",
    email: "公式ページ参照",
    inquiryUrl: CONTACT_PAGE_URL,
    officeHours: "平日 9:00-17:00 または 10:00-17:00",
    tags: ["学生生活", "課外活動", "学生支援"],
    inquiryExamples: ["課外活動の手続き先を知りたい", "学生生活上の相談をどこに出せばよいか知りたい", "学生支援制度の窓口を案内してほしい"],
    cautionNotes: ["履修や成績そのものは学部・大学院事務が担当です。", "メンタル面やハラスメントは専用相談窓口につなぐのが適切です。"],
    sourceUrls: [CONTACT_PAGE_URL],
    status: "active",
    relatedSlugs: ["scholarship-support-desk", "student-counseling-room", "health-center-clinic"],
  },
  {
    slug: "it-support-desk",
    name: "総合情報センター",
    officialName: "法政大学 総合情報センター",
    shortDescription: "ID登録、PC貸出、情報システム利用に関する窓口。",
    longDescription:
      "パソコン貸し出しやID登録など、学生・教職員の情報環境を支える窓口です。市ケ谷・多摩・小金井にそれぞれ窓口があり、アカウントや端末に関する相談を受け付けます。",
    categoryId: "learning-it-consultation",
    audienceTypes: ["在学生", "大学院生", "教職員"],
    campusTypes: ["市ケ谷", "多摩", "小金井"],
    courseTypes: ["通学課程", "大学院", "専門職大学院", "通信教育部"],
    phone: "市ケ谷 03-3264-9636 / 多摩 042-783-2202 / 小金井 042-387-6089",
    email: "公式ページ参照",
    inquiryUrl: CONTACT_PAGE_URL,
    officeHours: "平日 9:00-17:00 / 土 一部 9:00-12:00",
    tags: ["IT", "アカウント", "PC貸出"],
    inquiryExamples: ["大学アカウントの登録方法を知りたい", "パソコン貸し出しの条件を確認したい", "情報システムの利用先を知りたい"],
    cautionNotes: ["履修制度そのものの質問は学部・大学院窓口が担当です。", "学内サービスごとに別ページへの誘導が入る場合があります。"],
    sourceUrls: [CONTACT_PAGE_URL],
    status: "active",
    relatedSlugs: ["student-center", "certificate-guidance", "correspondence-education-office"],
  },
  {
    slug: "student-counseling-room",
    name: "学生相談室",
    officialName: "法政大学 学生相談室",
    shortDescription: "学業継続の不安や対人関係、心身の悩みを相談できる窓口。",
    longDescription:
      "学業、生活、対人関係、心身の不調など、学生が抱えるさまざまな悩みを相談できる窓口です。市ケ谷・多摩・小金井に拠点があり、必要に応じて学内外の支援につなぎます。",
    categoryId: "learning-it-consultation",
    audienceTypes: ["在学生"],
    campusTypes: ["市ケ谷", "多摩", "小金井"],
    courseTypes: ["通学課程"],
    phone: "市ケ谷 03-3264-9493 / 多摩 042-783-2158 / 小金井 042-387-6050",
    email: "公式ページ参照",
    inquiryUrl: CONTACT_PAGE_URL,
    officeHours: "相談室サイト参照",
    tags: ["相談", "メンタルヘルス", "学業継続"],
    inquiryExamples: ["授業に通うのがつらい状況を相談したい", "対人関係の悩みを話したい", "休学を考える前に相談したい"],
    cautionNotes: ["緊急性が高い場合は学外の緊急支援窓口も併用してください。", "制度手続きそのものは担当部署の確認が必要です。"],
    sourceUrls: [CONTACT_PAGE_URL],
    status: "active",
    relatedSlugs: ["student-center", "disability-support-room", "health-center-clinic"],
  },
  {
    slug: "disability-support-room",
    name: "障がい学生支援室",
    officialName: "法政大学 障がい学生支援室",
    shortDescription: "合理的配慮や学修支援に関する相談窓口。",
    longDescription:
      "障がいのある学生に対する合理的配慮や学修支援に関する相談窓口です。市ケ谷・多摩・小金井に拠点があり、授業担当者や関係部署と連携しながら支援導線を整えます。",
    categoryId: "learning-it-consultation",
    audienceTypes: ["在学生", "保証人", "教職員"],
    campusTypes: ["市ケ谷", "多摩", "小金井"],
    courseTypes: ["通学課程"],
    phone: "市ケ谷 03-3264-6718 / 多摩 042-783-4038 / 小金井 042-387-4556",
    email: "公式ページ参照",
    inquiryUrl: CONTACT_PAGE_URL,
    officeHours: "支援室サイト参照",
    tags: ["合理的配慮", "学修支援", "支援室"],
    inquiryExamples: ["授業で必要な合理的配慮を相談したい", "学修環境について事前に相談したい", "支援申請の流れを確認したい"],
    cautionNotes: ["履修制度や成績評価の最終判断は所属窓口と授業担当側の確認が必要です。", "心理面の継続相談は学生相談室と併用になることがあります。"],
    sourceUrls: [CONTACT_PAGE_URL],
    status: "active",
    relatedSlugs: ["student-counseling-room", "student-center", "health-center-clinic"],
  },
  {
    slug: "health-center-clinic",
    name: "診療所",
    officialName: "法政大学 診療所",
    shortDescription: "健康診断、診療、体調相談の窓口。",
    longDescription:
      "健康診断や診療に関する問い合わせ窓口です。市ケ谷・多摩・小金井に診療所があり、体調不良時や保健関連の相談先として使えます。",
    categoryId: "learning-it-consultation",
    audienceTypes: ["在学生", "大学院生"],
    campusTypes: ["市ケ谷", "多摩", "小金井"],
    courseTypes: ["通学課程", "大学院", "専門職大学院"],
    phone: "市ケ谷 03-3264-9503 / 多摩 042-783-2161 / 小金井 042-387-6051",
    email: "公式ページ参照",
    inquiryUrl: CONTACT_PAGE_URL,
    officeHours: "診療所サイト参照",
    tags: ["健康診断", "診療", "保健"],
    inquiryExamples: ["健康診断や診療の案内を確認したい", "診療所の受付方法を知りたい", "体調不良時の相談先を確認したい"],
    cautionNotes: ["診療時間はキャンパスや時期で変わるため専用案内を確認してください。", "心理面の継続相談は学生相談室の利用が適切な場合があります。"],
    sourceUrls: [CONTACT_PAGE_URL],
    status: "active",
    relatedSlugs: ["student-counseling-room", "student-center", "disability-support-room"],
  },
  {
    slug: "career-center",
    name: "キャリアセンター",
    officialName: "法政大学 キャリアセンター",
    shortDescription: "就職活動、進路形成、インターンに関する窓口。",
    longDescription:
      "就職支援や進路形成に関する総合窓口です。市ケ谷・多摩・小金井に事務課があり、インターンシップ、就職活動、進路相談の入口として機能します。",
    categoryId: "career-global-diversity",
    audienceTypes: ["在学生", "大学院生"],
    campusTypes: ["市ケ谷", "多摩", "小金井"],
    courseTypes: ["通学課程", "大学院", "専門職大学院"],
    phone: "市ケ谷 03-3264-9604 / 多摩 042-783-2173 / 小金井 042-387-6046",
    email: "career@hosei.ac.jp",
    inquiryUrl: CAREER_URL,
    officeHours: "平日 9:00-17:00 / 土 9:00-12:00",
    tags: ["就職", "インターン", "キャリア"],
    inquiryExamples: ["就職活動の相談をしたい", "インターンシップ情報を確認したい", "進路形成の支援を受けたい"],
    cautionNotes: ["履修相談や留学手続きは別窓口です。", "キャンパスごとに利用できるイベントや講座が異なる場合があります。"],
    sourceUrls: [CAREER_URL, CONTACT_PAGE_URL],
    status: "active",
    relatedSlugs: ["global-education-center", "student-center", "certificate-guidance"],
  },
  {
    slug: "global-education-center",
    name: "グローバル教育センター",
    officialName: "法政大学 グローバル教育センター",
    shortDescription: "留学、国際交流、外国人留学生支援の窓口。",
    longDescription:
      "留学と国際交流に関する相談窓口です。国際交流課と国際支援課の両系統があり、派遣留学と外国人留学生支援の双方を案内します。",
    categoryId: "career-global-diversity",
    audienceTypes: ["在学生", "受験検討者", "留学生"],
    campusTypes: ["共通"],
    courseTypes: ["通学課程", "大学院"],
    phone: "03-3264-9315（留学） / 03-3264-5475（外国人留学生）",
    email: "global@hosei.ac.jp",
    inquiryUrl: GLOBAL_URL,
    officeHours: "平日 9:00-17:00",
    tags: ["留学", "国際交流", "外国人留学生"],
    inquiryExamples: ["派遣留学の制度を確認したい", "外国人留学生向けの支援を知りたい", "国際プログラムの相談をしたい"],
    cautionNotes: ["費用や奨学金は学生センター側の制度確認が必要になる場合があります。", "学部独自プログラムは各学部窓口の確認も必要です。"],
    sourceUrls: [GLOBAL_URL, CONTACT_PAGE_URL],
    status: "active",
    relatedSlugs: ["career-center", "scholarship-support-desk", "admissions-center"],
  },
  {
    slug: "certificate-guidance",
    name: "証明書・各種手続案内",
    officialName: "法政大学 各種申請・証明書案内",
    shortDescription: "証明書発行や学籍手続への導線をまとめた案内枠。",
    longDescription:
      "証明書の発行、休学・復学、退学、学生証再交付などの共通手続きを探すときの案内枠です。実際の提出先は所属課程や所属学部によって変わるため、この案内から各窓口へ振り分ける使い方を想定しています。",
    categoryId: "admissions-common",
    audienceTypes: ["在学生", "大学院生", "卒業生"],
    campusTypes: ["共通"],
    courseTypes: ["通学課程", "大学院", "専門職大学院", "通信教育部"],
    phone: "所属窓口または証明書発行ページ参照",
    email: "公式ページ参照",
    inquiryUrl: STUDENT_GUIDE_URL,
    officeHours: "手続ごとに異なるため公式案内参照",
    tags: ["証明書", "休学", "復学", "手続"],
    inquiryExamples: ["在学証明書や成績証明書の発行方法を知りたい", "休学や復学の手続き先を確認したい", "学生証再交付の流れを知りたい"],
    cautionNotes: ["所属学部・研究科によって最終提出先が変わります。", "急ぎの証明書発行は公式ページの受付条件を必ず確認してください。"],
    sourceUrls: [CONTACT_PAGE_URL, STUDENT_GUIDE_URL],
    status: "info",
    relatedSlugs: ["student-center", "law-faculty-office", "graduate-school-general-office"],
  },
  {
    slug: "public-relations-office",
    name: "総長室広報課",
    officialName: "法政大学 総長室広報課",
    shortDescription: "取材・広報全般の問い合わせ窓口。",
    longDescription:
      "大学全体の取材依頼や広報問い合わせを受ける窓口です。学部・研究所・イベントに関する外部からの連絡を整理し、適切な案内先につなぎます。",
    categoryId: "research-public-alumni",
    audienceTypes: ["学外関係者", "報道関係者", "卒業生"],
    campusTypes: ["共通"],
    courseTypes: ["共通"],
    phone: "03-3264-9240",
    email: "公式ページ参照",
    inquiryUrl: CONTACT_PAGE_URL,
    officeHours: "平日 9:00-17:00",
    tags: ["広報", "取材", "大学紹介"],
    inquiryExamples: ["大学への取材依頼を出したい", "大学全体の広報窓口を知りたい", "学外向けの問い合わせ先を確認したい"],
    cautionNotes: ["教員個人への直接連絡ではなく大学窓口としての案内です。", "研究助成や共同研究の相談は研究開発センター側が適切です。"],
    sourceUrls: [CONTACT_PAGE_URL],
    status: "active",
    relatedSlugs: ["research-development-center", "admissions-center", "hosei-junior-senior-high-school"],
  },
  {
    slug: "research-development-center",
    name: "研究開発センター",
    officialName: "法政大学 研究開発センター",
    shortDescription: "研究助成、受託研究、共同研究に関する共通窓口。",
    longDescription:
      "受託研究、共同研究、各種研究助成、外部資金、公募情報などを扱う研究支援窓口です。研究科や教員側の研究関連事務のハブとして利用できます。",
    categoryId: "research-public-alumni",
    audienceTypes: ["研究者", "大学院生", "学外連携担当"],
    campusTypes: ["共通"],
    courseTypes: ["大学院", "共通"],
    phone: "03-5228-1243",
    email: "公式ページ参照",
    inquiryUrl: CONTACT_PAGE_URL,
    officeHours: "平日 9:00-17:00",
    tags: ["研究助成", "共同研究", "外部資金"],
    inquiryExamples: ["受託研究や共同研究の相談をしたい", "外部資金の案内を確認したい", "研究助成制度の窓口を知りたい"],
    cautionNotes: ["学生生活や履修の窓口ではありません。", "研究科固有の学籍事務は大学院側窓口の確認が必要です。"],
    sourceUrls: [CONTACT_PAGE_URL],
    status: "active",
    relatedSlugs: ["graduate-school-general-office", "public-relations-office", "mba-office"],
  },
  {
    slug: "correspondence-education-office",
    name: "通信教育部事務部",
    officialName: "法政大学 通信教育部事務部",
    shortDescription: "通信教育部の履修、出願、学費を扱う専用窓口。",
    longDescription:
      "通信教育部に所属する学生や受験検討者向けの専用窓口です。通学課程とは制度が異なるため、通信教育部の相談はこの窓口から始めるのが最も安全です。",
    categoryId: "correspondence-attached",
    audienceTypes: ["通信教育部学生", "受験検討者"],
    campusTypes: ["共通"],
    courseTypes: ["通信教育部"],
    phone: "03-3264-6150",
    email: "tsushin@hosei.ac.jp",
    inquiryUrl: CORRESPONDENCE_URL,
    officeHours: "平日 9:00-17:00",
    tags: ["通信教育部", "スクーリング", "学費"],
    inquiryExamples: ["通信教育部の出願方法を知りたい", "スクーリング申込の流れを確認したい", "通信教育部の学費制度を知りたい"],
    cautionNotes: ["通学課程の学部・大学院とは制度が大きく異なります。", "アカウントやシステム不具合は総合情報センター連携になる場合があります。"],
    sourceUrls: [CORRESPONDENCE_URL, CONTACT_PAGE_URL],
    status: "active",
    relatedSlugs: ["admissions-center", "finance-division", "it-support-desk"],
  },
];

const facultySeeds: DepartmentSeed[] = [
  facultyOffice({ slug: "law-faculty-office", name: "法学部", categoryId: "ichigaya-faculty", campus: "市ケ谷", phone: "03-3264-9323", officeHours: "平日 10:00-16:00 / 4月・9月は 9:00-17:00 / 土 9:00-12:00" }),
  facultyOffice({ slug: "letters-faculty-office", name: "文学部", categoryId: "ichigaya-faculty", campus: "市ケ谷", phone: "03-3264-9324", officeHours: "平日 10:00-16:00 / 4月・9月は 9:00-17:00 / 土 9:00-12:00" }),
  facultyOffice({ slug: "business-administration-faculty-office", name: "経営学部", categoryId: "ichigaya-faculty", campus: "市ケ谷", phone: "03-3264-9332", officeHours: "平日 10:00-16:00 / 4月・9月は 9:00-17:00 / 土 9:00-12:00" }),
  facultyOffice({ slug: "intercultural-communication-faculty-office", name: "国際文化学部", categoryId: "ichigaya-faculty", campus: "市ケ谷", phone: "03-3264-9345", officeHours: "平日 10:00-16:00 / 4月・9月は 9:00-17:00 / 土 9:00-12:00" }),
  facultyOffice({ slug: "human-environment-faculty-office", name: "人間環境学部", categoryId: "ichigaya-faculty", campus: "市ケ谷", phone: "03-3264-9327", officeHours: "平日 10:00-16:00 / 4月・9月は 9:00-17:00 / 土 9:00-12:00" }),
  facultyOffice({ slug: "career-design-faculty-office", name: "キャリアデザイン学部", categoryId: "ichigaya-faculty", campus: "市ケ谷", phone: "03-3264-9341", officeHours: "平日 10:00-16:00 / 4月・9月は 9:00-17:00 / 土 9:00-12:00" }),
  facultyOffice({ slug: "gis-faculty-office", name: "GIS（グローバル教養学部）", categoryId: "ichigaya-faculty", campus: "市ケ谷", phone: "03-3264-5805", officeHours: "平日 10:00-16:00 / 4月・9月は 9:00-17:00 / 土 9:00-12:00" }),
  facultyOffice({ slug: "economics-faculty-office", name: "経済学部", categoryId: "tama-faculty", campus: "多摩", phone: "042-783-2503", officeHours: "平日 9:00-17:00 / 土 9:00-12:00" }),
  facultyOffice({ slug: "sociology-faculty-office", name: "社会学部", categoryId: "tama-faculty", campus: "多摩", phone: "042-783-2379", officeHours: "平日 9:00-17:00 / 土 9:00-12:00" }),
  facultyOffice({ slug: "social-wellbeing-faculty-office", name: "現代福祉学部", categoryId: "tama-faculty", campus: "多摩", phone: "042-783-2806", officeHours: "平日 9:00-17:00 / 土 9:00-12:00" }),
  facultyOffice({ slug: "sports-health-faculty-office", name: "スポーツ健康学部", categoryId: "tama-faculty", campus: "多摩", phone: "042-783-3003", officeHours: "平日 9:00-17:00 / 土 9:00-12:00" }),
  facultyOffice({ slug: "ssi-office", name: "SSI（スポーツ・サイエンス・インスティテュート）", categoryId: "tama-faculty", campus: "多摩", phone: "公式ページ参照", officeHours: "公式ページ参照" }),
  facultyOffice({ slug: "design-engineering-faculty-office", name: "デザイン工学部", categoryId: "koganei-faculty", campus: "市ケ谷", phone: "03-5228-1347", officeHours: "平日 10:00-16:00 / 土 閉室" }),
  facultyOffice({ slug: "computer-science-faculty-office", name: "情報科学部", categoryId: "koganei-faculty", campus: "小金井", phone: "042-387-6023", officeHours: "平日 10:00-16:00 / 4月は 9:00-17:00 / 土 閉室" }),
  facultyOffice({ slug: "science-engineering-faculty-office", name: "理工学部", categoryId: "koganei-faculty", campus: "小金井", phone: "042-387-6033", officeHours: "平日 10:00-16:00 / 4月は 9:00-17:00 / 土 閉室" }),
  facultyOffice({ slug: "life-sciences-faculty-office", name: "生命科学部", categoryId: "koganei-faculty", campus: "小金井", phone: "042-387-6406", officeHours: "平日 10:00-16:00 / 4月は 9:00-17:00 / 土 閉室" }),
];

const graduateSeeds: DepartmentSeed[] = [
  graduateOffice({
    slug: "graduate-school-general-office",
    name: "大学院総合窓口",
    officialName: "法政大学 大学院事務室（人文・国際文化・経済・法・政治・社会・経営）",
    categoryId: "graduate-school",
    campusTypes: ["市ケ谷", "多摩"],
    phone: "03-5228-0550〜0552",
    officeHours: "平日 9:00-17:00 / 土 9:00-12:00 / 授業期間外は閉室",
    tags: ["大学院", "人文科学研究科", "経済学研究科", "法学研究科"],
    inquiryExamples: ["人文科学研究科や国際文化研究科の出願方法を確認したい", "経済・法・政治・社会・経営系研究科の履修や研究指導を相談したい", "大学院の論文提出や学位申請の流れを知りたい"],
  }),
  graduateOffice({
    slug: "social-policy-graduate-office",
    name: "政策・社会系大学院窓口",
    officialName: "法政大学 政策創造・公共政策・キャリアデザイン・連帯社会系大学院窓口",
    categoryId: "graduate-school",
    campusTypes: ["市ケ谷"],
    phone: "03-3264-6630",
    officeHours: "平日 9:00-18:40 / 授業期間外 9:00-17:00 / 土 9:00-17:00",
    tags: ["政策創造研究科", "公共政策研究科", "キャリアデザイン学研究科", "連帯社会インスティテュート"],
    inquiryExamples: ["政策創造研究科や公共政策研究科の出願相談をしたい", "キャリアデザイン学研究科や連帯社会インスティテュートの履修を確認したい", "地域創造インスティテュートの制度を知りたい"],
  }),
  graduateOffice({
    slug: "human-social-graduate-office",
    name: "人間社会・スポーツ健康大学院窓口",
    officialName: "法政大学 人間社会研究科・スポーツ健康学研究科窓口",
    categoryId: "graduate-school",
    campusTypes: ["多摩"],
    phone: "人間社会 042-783-4047 / スポーツ健康 042-783-3003",
    officeHours: "平日 9:00-17:00 / 土 9:00-12:00",
    tags: ["人間社会研究科", "スポーツ健康学研究科", "多摩大学院"],
    inquiryExamples: ["人間社会研究科の出願方法を知りたい", "スポーツ健康学研究科の研究指導や学位申請を確認したい", "多摩キャンパスの大学院窓口を知りたい"],
  }),
  graduateOffice({
    slug: "science-graduate-office",
    name: "理工系大学院窓口",
    officialName: "法政大学 情報科学・理工・IIST系大学院窓口",
    categoryId: "graduate-school",
    campusTypes: ["小金井"],
    phone: "042-387-6014",
    officeHours: "平日 10:00-16:00 / 4月は 9:00-17:00 / 土 閉室",
    tags: ["情報科学研究科", "理工学研究科", "IIST", "小金井大学院"],
    inquiryExamples: ["情報科学研究科や理工学研究科の出願方法を知りたい", "総合理工学インスティテュートの履修や研究指導を確認したい", "小金井系大学院の論文提出先を知りたい"],
  }),
  graduateOffice({
    slug: "design-graduate-office",
    name: "デザイン工学研究科窓口",
    officialName: "法政大学 デザイン工学研究科窓口",
    categoryId: "graduate-school",
    campusTypes: ["市ケ谷"],
    phone: "03-5228-1347",
    officeHours: "平日 10:00-16:00 / 土 閉室",
    tags: ["デザイン工学研究科", "市ケ谷大学院"],
    inquiryExamples: ["デザイン工学研究科の出願方法を知りたい", "市ケ谷側の理工系大学院窓口を確認したい", "デザイン工学研究科の学位申請手続きを知りたい"],
  }),
  graduateOffice({
    slug: "law-school-office",
    name: "法科大学院窓口",
    officialName: "法政大学 法務研究科（法科大学院）窓口",
    categoryId: "graduate-school",
    campusTypes: ["市ケ谷"],
    phone: "03-3264-9039",
    officeHours: "平日 9:00-17:00",
    tags: ["法務研究科", "法科大学院", "専門職大学院"],
    inquiryExamples: ["法科大学院の出願や説明会情報を知りたい", "法務研究科の履修や学修支援を相談したい", "法科大学院の手続窓口を確認したい"],
  }),
  graduateOffice({
    slug: "mba-office",
    name: "経営大学院窓口",
    officialName: "法政大学 イノベーション・マネジメント研究科（経営大学院）窓口",
    categoryId: "graduate-school",
    campusTypes: ["市ケ谷"],
    phone: "03-3264-4341",
    officeHours: "平日 9:00-18:40 / 授業期間外 9:00-17:00 / 土 9:00-17:00",
    tags: ["イノベーション・マネジメント研究科", "経営大学院", "専門職大学院"],
    inquiryExamples: ["経営大学院の出願方法を知りたい", "イノベーション・マネジメント研究科の授業や履修を確認したい", "専門職大学院の窓口を知りたい"],
  }),
];

const attachedSchoolSeeds: DepartmentSeed[] = [
  {
    slug: "hosei-junior-senior-high-school",
    name: "法政大学中学高等学校",
    officialName: "法政大学中学高等学校",
    shortDescription: "学校案内や入学相談を扱う付属校窓口。",
    longDescription: "法政大学中学高等学校に関する入学案内、学校生活、説明会、各種問い合わせを受ける窓口です。大学の学部窓口とは制度が異なるため、付属校に関する確認は学校公式案内を起点にするのが安全です。",
    categoryId: "correspondence-attached",
    audienceTypes: ["受験検討者", "保護者"],
    campusTypes: ["付属校"],
    courseTypes: ["付属校"],
    phone: "0422-79-6230",
    email: "公式ページ参照",
    inquiryUrl: "https://www.hosei.ed.jp/",
    officeHours: "平日 9:00-17:00 / 土 9:00-12:00",
    tags: ["付属校", "中学高等学校", "説明会"],
    inquiryExamples: ["中高の説明会情報を知りたい", "出願方法や入試制度を確認したい", "学校生活について問い合わせたい"],
    cautionNotes: ["大学学部の入試とは別制度です。", "最新情報は学校公式サイトで確認してください。"],
    sourceUrls: [CONTACT_PAGE_URL, "https://www.hosei.ed.jp/"],
    status: "active",
    relatedSlugs: ["admissions-center", "public-relations-office"],
  },
  {
    slug: "hosei-daini-junior-senior-high-school",
    name: "法政大学第二中・高等学校",
    officialName: "法政大学第二中・高等学校",
    shortDescription: "学校案内や入学相談を扱う付属校窓口。",
    longDescription: "法政大学第二中・高等学校に関する入学案内、学校生活、説明会、各種問い合わせを受ける窓口です。大学の学部窓口とは制度が異なるため、学校公式案内を起点に確認するのが安全です。",
    categoryId: "correspondence-attached",
    audienceTypes: ["受験検討者", "保護者"],
    campusTypes: ["付属校"],
    courseTypes: ["付属校"],
    phone: "044-711-4321",
    email: "公式ページ参照",
    inquiryUrl: "https://www.hosei2.ed.jp/",
    officeHours: "平日 9:00-17:00 / 土 9:00-12:00",
    tags: ["付属校", "中高", "説明会"],
    inquiryExamples: ["第二中・高の説明会情報を知りたい", "出願方法や入試制度を確認したい", "学校生活について問い合わせたい"],
    cautionNotes: ["大学学部の入試とは別制度です。", "最新情報は学校公式サイトで確認してください。"],
    sourceUrls: [CONTACT_PAGE_URL, "https://www.hosei2.ed.jp/"],
    status: "active",
    relatedSlugs: ["admissions-center", "public-relations-office"],
  },
  {
    slug: "hosei-kokusai-high-school",
    name: "法政大学国際高等学校",
    officialName: "法政大学国際高等学校",
    shortDescription: "学校案内や入学相談を扱う付属校窓口。",
    longDescription: "法政大学国際高等学校に関する入学案内、学校生活、説明会、各種問い合わせを受ける窓口です。大学学部の案内とは別系統なので、学校ごとの公式案内を起点にするのが安全です。",
    categoryId: "correspondence-attached",
    audienceTypes: ["受験検討者", "保護者"],
    campusTypes: ["付属校"],
    courseTypes: ["付属校"],
    phone: "045-571-4482",
    email: "公式ページ参照",
    inquiryUrl: "https://kokusai-high.ws.hosei.ac.jp/",
    officeHours: "平日 9:00-17:00 / 土 9:00-12:00",
    tags: ["付属校", "国際高等学校", "説明会"],
    inquiryExamples: ["国際高校の説明会情報を知りたい", "出願方法や入試制度を確認したい", "学校生活について問い合わせたい"],
    cautionNotes: ["大学学部の入試とは別制度です。", "最新情報は学校公式サイトで確認してください。"],
    sourceUrls: [CONTACT_PAGE_URL, "https://kokusai-high.ws.hosei.ac.jp/"],
    status: "active",
    relatedSlugs: ["admissions-center", "public-relations-office"],
  },
];

export const departments: Department[] = [
  ...supportSeeds,
  ...facultySeeds,
  ...graduateSeeds,
  ...attachedSchoolSeeds,
].map(office);

export const relations: DepartmentRelation[] = [
  { id: "rel-01", fromDepartmentId: "dept-01", toDepartmentId: "dept-15", relationType: "journey", label: "学部窓口へ流れる前の入試入口", weight: 3, note: "入学センターから各学部事務へ移る導線がよく発生します。" },
  { id: "rel-02", fromDepartmentId: "dept-02", toDepartmentId: "dept-03", relationType: "journey", label: "学費相談と奨学金相談は連続しやすい", weight: 3, note: "学費納入が難しい相談では、財務部財務課と奨学金窓口を続けて確認することが多いです。" },
  { id: "rel-03", fromDepartmentId: "dept-03", toDepartmentId: "dept-04", relationType: "collaboration", label: "生活支援は学生センターと連携しやすい", weight: 2, note: "奨学金、アルバイト、住まい相談は学生センターの導線と重なります。" },
  { id: "rel-04", fromDepartmentId: "dept-04", toDepartmentId: "dept-06", relationType: "journey", label: "学生生活相談から相談室へつながりやすい", weight: 2, note: "学生生活上の困りごとが心理相談や継続支援につながるケースを想定しています。" },
  { id: "rel-05", fromDepartmentId: "dept-05", toDepartmentId: "dept-14", relationType: "misroute", label: "IT相談と通信教育の相談は切り分けが必要", weight: 2, note: "制度質問とアカウント・端末質問の窓口が分かれます。" },
  { id: "rel-06", fromDepartmentId: "dept-08", toDepartmentId: "dept-09", relationType: "journey", label: "キャリア支援と留学支援の接続", weight: 1, note: "海外経験と進路形成をセットで相談するケースを想定しています。" },
  { id: "rel-07", fromDepartmentId: "dept-06", toDepartmentId: "dept-07", relationType: "collaboration", label: "相談支援と合理的配慮は重なりやすい", weight: 1, note: "心理的な相談と学修支援上の配慮が同時に必要になる場合があります。" },
  { id: "rel-08", fromDepartmentId: "dept-10", toDepartmentId: "dept-15", relationType: "misroute", label: "証明書は所属先ごとに提出先が変わる", weight: 2, note: "共通案内だけで完結せず、学部・大学院窓口で分岐します。" },
  { id: "rel-09", fromDepartmentId: "dept-11", toDepartmentId: "dept-13", relationType: "collaboration", label: "広報と研究支援の連携", weight: 1, note: "研究成果の対外発信や外部問い合わせで連携が発生します。" },
  { id: "rel-10", fromDepartmentId: "dept-01", toDepartmentId: "dept-35", relationType: "misroute", label: "大学入試と付属校入試は別経路", weight: 3, note: "大学学部の入試窓口と付属校の入試窓口は制度が異なるため、早めの切り分けが必要です。" },
];

export const scrapeJobs: ScrapeJob[] = [
  { id: "job-01", targetUrl: CONTACT_PAGE_URL, status: "success", startedAt: "2026-04-10T21:45:00+09:00", finishedAt: "2026-04-10T22:03:00+09:00", resultSummary: "公式問い合わせページを再取得し、学部・大学院・付属校を含む窓口一覧を更新しました。" },
  { id: "job-02", targetUrl: STUDENT_GUIDE_URL, status: "success", startedAt: "2026-04-10T22:04:00+09:00", finishedAt: "2026-04-10T22:12:00+09:00", resultSummary: "学生サービス系の導線を確認し、相談・学費・IT関連の分類を補強しました。" },
  { id: "job-03", targetUrl: CORRESPONDENCE_URL, status: "success", startedAt: "2026-04-10T22:12:00+09:00", finishedAt: "2026-04-10T22:17:00+09:00", resultSummary: "通信教育部の専用窓口情報を反映しました。" },
];

export function getDepartmentBySlug(slug: string) {
  return departments.find((department) => department.slug === slug);
}

export function getCategoryById(categoryId: string) {
  return categories.find((category) => category.id === categoryId);
}
